### ISSUE TITLE
Would like to know what resources were used to build this

### ISSUE THREAD

**Issue by Enovale** [quimmedes/HelloXamarinSDL2-CS#1]
I've looked at other similar SDL2 CS projects and I recognize most of the elements being used but some specific examples/links/instructions for how you're building the natives and the SDL_JNI.jar would be appreciated.

**Comment by quimmedes** [comment]
This project is exclusively for Android, if you want to run it on Windows I would recommend the Vuala Engine, it's a project running SDL2 targeting desktop. I'm trying to make a MAUI project with all platforms, but it seems it will just work on Mac so I postpone it, and focus first on each individually. 

So about compile it yourself the SDL source code will provide everything you need to but you will also need some individual tools knowledge and also a bit of Cmake or Make. It's easier with Cmake

You have to build the android project as library and you will get .aar file that contains everything inside like a .zip you will just need to extract it, there will be the natives .so and .jar libraries, but it won't  work with Xamarin/.net targeting android as simple as that, because you need to adapt the code to work with .Net. For desktop windows, linux, etc. you can just use Cmake to build them or use NuGet SDL libraries, use the sdl-cs bindings avaiable and it works as simple as that or just use the binaries avaiable in the SDL github page.


Some helpful Resources
https://lazyfoo.net/tutorials/SDL/52_hello_mobile/index.php

https://github.com/pvallet/hello-sdl2-android
